### ISSUE TITLE
stays at "transreid.train INFO: start training "

### ISSUE THREAD

**Issue by hlmhlr** [damo-cv/TransReID#23]
Hi, 

Your work regarding Reid using Transformers is really appreciated. 

I am trying to train the "Market" dataset using the terminal command: 
python train.py --config_file configs/Market/vit_transreid_stride.yml MODEL.DEVICE_ID "('0')"
Model is initiallized but it remains in the state "transreid.train INFO: start training" and do not proceed further for training. While trying to debug, I found that program enters in the main loop of epochs but doesn't enters in the nested loop as shown below:  
https://github.com/heshuting555/TransReID/blob/5901746360fc5c02b415f4dafb191d8d20d6e1c2/processor/processor.py#L43-L50
I don't know how to resolve this issue. Meanwhile i also looked into [this](https://github.com/heshuting555/TransReID/issues/10) but this didn't help me out. I shall be thankful for the fruitful response. 

Kind Regards,

**Comment by heshuting555** [comment]
It is strange. Do you clean up other processes? You can stop and kill other process and then try again.

Thank you for your attention.

**Comment by hlmhlr** [comment]
> It is strange. Do you clean up other processes? You can stop and kill other processes and then try again.
> 
> Thank you for your attention.

Thanks for your response. 
I don't know what do you mean by other processes here but i closed all other running apps, even restarted the machine and then re-ran the training command but still facing the same state.

**Comment by zackzhao1** [comment]
i meet the same state and has solving it.
use smaller batchsize.

**Comment by hlmhlr** [comment]
> i meet the same state and has solving it.
> use smaller batchsize.
Hi,
I have already tried "IMS_PER_BATCH: 1" but still facing the same issue. Could you please share your log file so that I may compare the parameters for troubleshooting purposes?

**Comment by Tracy-git** [comment]
> 分

i use bigger batchsize:16 to fix this problems . my gpu is 3080 10GB

**Comment by hlmhlr** [comment]
> 



> 

Yes, it worked for me too. thanks.
