### ISSUE TITLE
would you please provide seperate feature_extractor file . It will be a greathelp

### ISSUE THREAD

**Issue by ssbilakeri** [damo-cv/TransReID#24]

**Comment by heshuting555** [comment]
you can follow the code in the processor.py
`    for n_iter, (img, pid, camid, camids, target_view, imgpath) in enumerate(val_loader):
        with torch.no_grad():
            img = img.to(device)
            camids = camids.to(device)
            target_view = target_view.to(device)
            feat = model(img, cam_label=camids, view_label=target_view)

`
Thank you for your attention/
