### ISSUE TITLE
the influence of batch_size

### ISSUE THREAD

**Issue by nanggn** [damo-cv/TransReID#25]
Hi, I run the code as: python train.py --config_file configs/VeRi/vit_transreid_stride.yml MODEL.DEVICE_ID "('0')" and don't change the arguments except  batch_size, because of limited GPU. I set batch_size as 12 and mAP for VeRi-776 dataset is 70.3%, 10% lower than the original.
      Is this normal or something wrong happened?

**Comment by heshuting555** [comment]
I think it is normal. Triplet loss needs proper batch size to learn discriminative feature. You can set batch to 32. It will not be so bad.

**Comment by nanggn** [comment]
OK. Thanks a lot.
