### ISSUE TITLE
Training on KITTI Tracking benchmark

### ISSUE THREAD

**Issue by tehseenmayar** [damo-cv/TransReID#26]
Hi, Thanks for your great work
Do you have code for testing your solution on KITTI Tracking benchmark or if you can guide me how to test it against KITTI Tracking benchmark?
I would really appreciate any help

**Comment by heshuting555** [comment]
Thank you for your attention. I haven't tried it. This method is used for object re-identification instead of tracking. You can try to use this code in similarity learning in tracking.
