### ISSUE TITLE
Question about Overlapping Patches

### ISSUE THREAD

**Issue by zzzmm1** [damo-cv/TransReID#36]
As shown in your paper, the shape of area where two adjacent patches overlap is (P - S) x P.
When P = S = 16, does this degenerate into a non-overlapping patches?
[https://github.com/damo-cv/TransReID/blob/main/model/backbones/vit_pytorch.py](url)
In your vit_pytorch.py, is the main difference between PatchEmbed and PatchEmbed_overlap that in Conv2d, the kernel_size of the former is equal to stride and equal to patch_size, while the stride and kernel_size of the latter can be different?
Thanks a lot for your help.

**Comment by michuanhaohao** [comment]
When P = S = 16, does this degenerate into a non-overlapping patches?
