### ISSUE TITLE
Is it possible that pre-training weights have a big impact on the convergence of the network? Because I did not use pre-training weights, the map is only 38.8, how did you train it?

### ISSUE THREAD

**Issue by fakerhbj** [damo-cv/TransReID#37]
transreid.train INFO: mAP: 38.8%
 transreid.train INFO: CMC curve, Rank-1  :55.5%
 transreid.train INFO: CMC curve, Rank-5  :80.0%
 transreid.train INFO: CMC curve, Rank-10 :88.0%

**Comment by heshuting555** [comment]
Hello, vision transformer weight on imagenet datasets is critical for a downstream task like reid.
It is fair because R50 also use imagenet pretrained weight.
