### ISSUE TITLE
加载模型参数

### ISSUE THREAD

**Issue by Mfun82** [damo-cv/TransReID#38]
您好！我将跑了一半的模型保存，然后重新加载模型参数想要继续跑，发现在imagenet预训练模式下找不到base.cls_token，报错信息为：KeyError: 'base.cls_token'，这是为什么呢？self和finetune模式下不会报错，但精度很低。
期待您的回复！谢谢！

**Comment by michuanhaohao** [comment]
同学你好，加载自己训练的模型参数需要用self模式，恢复训练除了需要恢复模型的参数以外，学习率和优化器的参数也需要恢复。可以参考其他repo的resume training模式，比如Imagnet、DINO、fast-reid等repo。

**Comment by Mfun82** [comment]
谢谢！明白了！感谢您的时间！

**Comment by YuzhouPeng** [comment]
> 同学你好，加载自己训练的模型参数需要用self模式，恢复训练除了需要恢复模型的参数以外，学习率和优化器的参数也需要恢复。可以参考其他repo的resume training模式，比如Imagnet、DINO、fast-reid等repo。

请问一下如何用self模式？
