### ISSUE TITLE
Question about the cls token

### ISSUE THREAD

**Issue by siri-ya** [damo-cv/TransReID#40]
Awesome work of introducing transformer into ReID! But maybe I don't totaly understand the paper, having some confusion about the cls token. As shown in your paper, the cls token is a learnable embedding. And the code just initialize it as a parameter with normal distribution, and expand it to match the examples' shape in every batch. That is to say, the cls's value is no difference for each data when the model has completed training, Right? So I don't understand the meaning of setting it...
Thanks a lot for your help!

**Comment by michuanhaohao** [comment]
You can refer to BERT and ViT to better understand the [CLS] token. The [CLS] token is similar with the parameters of the center loss. We need give it a value as the initial value. But the value of the [CLS] token is related to Q,K,V, which are different for different data after the model inference. Therefore the [CLS] token is different for each data when the model has completed training.

**Comment by siri-ya** [comment]
Ohhh! I get it now. Thanks so much for your kindly reply!!
