### ISSUE TITLE
How to train on TransReID's pretrained Veri/VehicleID weights?

### ISSUE THREAD

**Issue by prsantiago** [damo-cv/TransReID#44]
I'm trying to train my custom dataset on your Veri/VehicleID pretrained weights but haven't got it right.

First approach was the simple:

<img width="421" alt="imagenet_pretrained" src="https://user-images.githubusercontent.com/25907634/147157018-cd702fb9-7f99-447a-8cbb-fdd7863f9591.png">

but got this error:

<img width="572" alt="error_imagenet" src="https://user-images.githubusercontent.com/25907634/147157049-33292cf4-3ac9-4a8e-9eb3-39bf95f30b77.png">

Second approach was changing `PRETRAIN_CHOICE: 'self'` and also on `train.py`:

<img width="575" alt="normal" src="https://user-images.githubusercontent.com/25907634/147158893-9a5a685a-9218-40ac-b4a5-5b10ff4d1f83.png">

but got this error:

<img width="505" alt="error_normal" src="https://user-images.githubusercontent.com/25907634/147158947-dfc18373-72cc-491e-8aa1-5b052d562a7a.png">

Third approach was basically the same as the second but change the `train.py`:

<img width="593" alt="finetune" src="https://user-images.githubusercontent.com/25907634/147159019-be3f3bea-0025-4143-a674-8f55a3967676.png">

the same error as the second approach

<img width="552" alt="error_finetune" src="https://user-images.githubusercontent.com/25907634/147159065-434d20f5-7962-4f27-a700-2b26f9d4db0b.png">

Can anyone guide me? Nowhere in the repo I have seen the code asking if `PRETRAIN_CHOICE` equals to `'self'` or `'finetune'`, but in `configs/default.py` it says that those are the remaining options.

<img width="652" alt="pretrain_choices" src="https://user-images.githubusercontent.com/25907634/147159628-ac47f32e-134e-43c1-a3c4-04756d984786.png">

**Comment by michuanhaohao** [comment]
I think you pre-trained your models with 21*21=441 patches but your fine-tuned your models with 16*16=256 patches. Maybe you can check here https://github.com/damo-cv/TransReID/blob/f1e1f8f1e3efb526f4b91698c037a47955ee3496/model/backbones/vit_pytorch.py#L428

I guess 'resize_pos_embed()' was not called.

**Comment by michuanhaohao** [comment]
You can choose 'self' version, but you should resize the position embedding before loading the checkpoint.
