### ISSUE TITLE
多卡训练

### ISSUE THREAD

**Issue by Mrkkew** [damo-cv/TransReID#45]
请问你们的模型可以jinx多卡并行训练吗？
你们在做实验时有这样训练并测试性能吗，对模型性能是否有影响？

**Comment by michuanhaohao** [comment]
我一直用4卡训练，性能基本上没啥影响，最多差0.1~0.2%。学习率和batch size要做线性的缩放，你可以参考我下面repo readme里面的四卡配置。八卡我没跑过，不知道有没有影响。

[https://github.com/michuanhaohao/TransReID-SSL/tree/main/transreid_pytorch](https://github.com/michuanhaohao/TransReID-SSL/tree/main/transreid_pytorch)

**Comment by buaa-luzhi** [comment]
@michuanhaohao 
我每次使用多卡训练时，在训练的过程中，每个50epochs进行测试，总是会卡住，没法测试。单卡没有这种问题，请问这该怎么解决呢，谢谢！
