### ISSUE TITLE
由特征表示可视化图像是怎么做的？

### ISSUE THREAD

**Issue by liyuke65535** [damo-cv/TransReID#58]
请问在你们工作的Figure 2中，通过cnn特征向量和transformer特征向量的可视化，是怎么做的？
![特征向量可视化](https://user-images.githubusercontent.com/39180877/171338559-873f1545-5bc0-44f2-ac95-a44fbce32be2.png)

**Comment by liyuke65535** [comment]
我的做法是使用的输入是256x128，那么在第一个block得到的特征维度是210x768(通道数)。那么把210reshape回21x10，然后把768通道数取平均值，得到21x10的特征图。请问这样的做法思路是对的吗？如果对的话，那么即使换成1024x512输入，特征图大概是85x42，似乎也没法达到论文图中这种效果。

![image](https://user-images.githubusercontent.com/39180877/171629388-c72e211b-b600-4086-bf63-72fa97c319b8.png)
这是我得到的特征图，似乎不能看出什么

**Comment by michuanhaohao** [comment]
输入1024*512，不要使用overlap（会破坏空间连续性），最后大概输出64*32的feature map，每个block都是这个大小，浅层的更细节一些，深层的更抽象一些

**Comment by 459737087** [comment]
Hello! How to visualization the result.
I can't find it

**Comment by 459737087** [comment]
@liyuke65535  Why closing it ...
