### ISSUE TITLE
Merge different entities!!!

### ISSUE THREAD

**Issue by image-rcdat** [damo-cv/TransReID#67]
Hi, Thanks for sharing your great work, as I see, you trained the model based on specific datasets which is used for specific entity, like human and vehicle.
so, I want to know, what would happen if we combine these datasets and train a single model?
Does the performance drop too bad?
I'm looking forward to your answer eagerly, Thanks

**Comment by heshuting555** [comment]
I didn't try it. But you can try it. But intuitively this will reduce performance, after all, the distribution of each dataset is different.
