### ISSUE TITLE
KeyError: 'base.cls_token'

### ISSUE THREAD

**Issue by Schatzmin** [damo-cv/TransReID#71]
你好，我在复现时用的是这里的预训练模型，结果报错：KeyError: 'base.cls_token'。请问是有什么问题了吗？
![image](https://user-images.githubusercontent.com/93251898/220310781-c897897a-4ffd-40b2-8017-8e792c4bdede.png)

**Comment by Schatzmin** [comment]
![image](https://user-images.githubusercontent.com/93251898/220313024-5c5ec5c9-7c76-46b1-a287-457466c9d3c8.png)
这一行报错了，应该是字典中没有'base.cls_token'键，或许是因为使用的预训练模型不一致？

**Comment by chen960** [comment]
你怎么解决的这个问题？

**Comment by Schatzmin** [comment]
> 你怎么解决的这个问题？

表里的model不是预训练模型，预训练模型在这里：
![Uploading image.png…]()

**Comment by Schatzmin** [comment]
> 你怎么解决的这个问题？

表里的model不是预训练模型，预训练模型在这里：
![image](https://github.com/damo-cv/TransReID/assets/93251898/dc190f7a-aeb6-4796-a1e3-cbfb4733ac7a)

**Comment by Schatzmin** [comment]
> 你怎么解决的这个问题？

表里面的model不是预训练模型，预训练模型在这里：
![image](https://github.com/damo-cv/TransReID/assets/93251898/dc190f7a-aeb6-4796-a1e3-cbfb4733ac7a)
