### ISSUE TITLE
Did you consider adding temporal info in side info?

### ISSUE THREAD

**Issue by SuperbTUM** [damo-cv/TransReID#73]
Hi authors, thanks for the hard work! I read you included camera and view information in your side information embedding. I wonder if you considered adding sequence information(at least Market1501 has such labeling info) as well. Camera and view are spatial info and there should be bias, but at the same time, sequence(different time periods for recording) may also introduce bias in re-id(day & night time, face & back to the camera). Thanks.

**Comment by heshuting555** [comment]
You can try it. But you need to consider whether it is a fair comparison.

**Comment by SuperbTUM** [comment]
Thanks, will do that.
